"""
Fixed list of reasons a reviewer must select when manually linking two
unmatched entries together (Manual Link screen). Sourced from
docs/Update Status.xlsx — kept as a single source of truth here so the
manual-link endpoint's validation and the frontend's dropdown options
(via the /status-reasons endpoint) never drift out of sync.
"""

STATUS_REASONS: list[str] = [
    "Adjusted against Disputed transaction",
    "Amount Mismatch",
    "Amount Mismatch - Matched with Ledger",
    "Closing Balance as per Company",
    "Closing Balance as per Party",
    "Company Credit Note Pertains to Prior Period",
    "Company Debit Note Pertains to Prior Period",
    "Company Internal Entries",
    "Company Invoice Pertains to Prior Period",
    "Company Other Entry Pertains to Prior Period",
    "Company Payment Entry Pertains to Prior Period",
    "Company Provision Entries",
    "Company Transfer Entries",
    "Credit Note Not In Party Open Item",
    "Credit Note booked subsequently by Company",
    "Credit Note booked subsequently by Party",
    "Credit Note not booked by Company",
    "Credit Note not booked by Party",
    "Credit Note not in Company Open Item",
    "Credit Note not in Party Open Item",
    "Debit Note / Credit Note Mismatch",
    "Debit Note Not In Company Open Item",
    "Debit Note Not In Party Open Item",
    "Debit Note booked subsequently by Company",
    "Debit Note booked subsequently by Party",
    "Debit Note not booked by Company",
    "Debit Note not booked by Party",
    "Duplicate Invoice Accounted by Company",
    "Duplicate TDS Booked by Company",
    "Excess payment accounted by Party",
    "GRN Done Invoice to be accounted",
    "GRN Done Invoice to be accounted - Amount Mismatch",
    "GST Amount on Hold by Company",
    "Interest on Bills discounting",
    "Invoice Amount Mismatch",
    "Invoice Booked And Adjusted",
    "Invoice Booked And Partial Payment Done",
    "Invoice Booked But Paid Subsequently by Company",
    "Invoice Booked But Paid Subsequently by Party",
    "Invoice Booked Post reco date",
    "Invoice Booked Subsequently by Company",
    "Invoice Booked Subsequently by Party",
    "Invoice Booked and Paid Subsequently by Company",
    "Invoice Booked and Paid Subsequently by Party",
    "Invoice Booked and Paid by Party",
    "Invoice booked & Paid by Vendor Financing",
    "Invoice booked and paid",
    "Invoice booked and paid after reco date",
    "Invoice booked and paid by Company",
    "Invoice booked but paid after reco date",
    "Invoice booked paid and adjusted",
    "Invoice excess amount claim party",
    "Invoice not booked by Company",
    "Invoice not booked by Party",
    "Invoice not in Company Open Item",
    "Invoice not in Party Open Item",
    "Invoice short amount claim party",
    "MSME Interest not shown by Party",
    "MSME Interest payment not accounted by Party",
    "Opening Balance as per Company",
    "Opening Balance as per Party",
    "Other Entries booked subsequently by Company",
    "Other Entries booked subsequently by Party",
    "Other entry not booked by Company",
    "Other entry not booked by Party",
    "Other entry not in Company Open Item",
    "Other entry not in Party Open Item",
    "Party Credit Note Pertains to Prior Period",
    "Party Debit Note Pertains to Prior Period",
    "Party Internal Entries",
    "Party Invoice Pertains to Prior Period",
    "Party Other Entry Pertains to Prior Period",
    "Party Payment Entry Pertains to Prior Period",
    "Payment Amount Mismatch",
    "Payment booked subsequently by Company",
    "Payment booked subsequently by Party",
    "Payment not booked by Company",
    "Payment not booked by Party",
    "Payment not knocked off by Company",
    "Payment not knocked off by party",
    "Reconciled",
    "Retention money not claimed by vendor",
    "Reversal Entries",
    "Short payment accounted by Party",
    "TCS Booked by Company",
    "TCS Booked by Party",
    "TDS Booked by Company",
    "TDS Booked by Party",
    "TDS booked subsequently by Company",
    "TDS booked subsequently by Party",
    "TDS not booked by Party",
    "Write off / Rounding off",
]

# O(1) membership checks for request validation.
VALID_STATUS_REASONS: frozenset[str] = frozenset(STATUS_REASONS)
