"""create_user_details_table

Revision ID: 361f1a83e1ae
Revises: 0c8129f326a8
Create Date: 2026-06-17 12:16:56.968055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361f1a83e1ae'
down_revision: Union[str, None] = '0c8129f326a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('designation_title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('business_unit', sa.String(length=255), nullable=False),
    sa.Column('group_company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('zone', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('office_mobile_no', sa.String(length=50), nullable=False),
    sa.Column('personal_mobile_no', sa.String(length=50), nullable=False),
    sa.Column('date_of_joining', sa.String(length=50), nullable=False),
    sa.Column('reporting_manager', sa.String(length=255), nullable=False),
    sa.Column('direct_manager_employee_id', sa.String(length=50), nullable=False),
    sa.Column('direct_manager_name', sa.String(length=255), nullable=False),
    sa.Column('direct_manager_email', sa.String(length=255), nullable=False),
    sa.Column('sap_user_id', sa.String(length=50), nullable=False),
    sa.Column('division_id', sa.String(length=50), nullable=False),
    sa.Column('territory_id', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_details_employee_id'), 'user_details', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_details_employee_id'), table_name='user_details')
    op.drop_table('user_details')
    # ### end Alembic commands ###
